name: habit_tracker_flutter
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_riverpod: ^1.0.0-dev.1
  flutter_svg: ^0.22.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  page_flip_builder: ^0.1.3
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/app-icon.png"
  image_path_android: "assets/app-icon.png"
  adaptive_icon_background: "assets/app-icon-background.png"
  adaptive_icon_foreground: "assets/app-icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
